version: '3.8'
services:
  db:
    image: postgres:16beta1-bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: default_password
      POSTGRES_DB: default_db
